### ISSUE TITLE
建築ミッション案ソフト開発検討

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#12]
# ミッション特有のステート
* モジュールの放出
* モジュールの移動
* モジュールの結合
***
# 各ステートフローチャート内で難しい点
***
## モジュールの移動について
**難しい点**
* 画角に収まっていなかった場合，どう動くのか.  
  * 先に写ったものを持ってしまう
* どちらのモジュールを動かすのか  
  ➡︎予め決めておく  
* 機体に近すぎた場合，どうするのか
* **二つが適切な位置にあるか**
* **モジュールを移動させる戦略**

**特徴**
* とりあえずARマーカーを探す  
  * 先に写ったものから移動する?  
* 二つのモジュールは最初から画角に収まっている想定

## モジュールの放出について
**難しい点**
* パラ分離後所定の位置に移動するなら.  
  * モジュールの位置決定
  * 決定した位置への走行
  * 上記位置への到着判断

**特徴**
* パラ分離後の位置で建設するなら難しくはない？
* モジュールの位置の決定

## モジュールの接続について
**難しい点**
* 掴めたかの判断基準は？  
  * ARマーカー等を導線にも貼る
* 掴めなかった時の処理は？
* 物理的に接続完了しているかの判断方法は？
* 草が一緒に刺さってしまう？  
  * 草があまりないところを放出場所に決定

**Comment by masato1004** [comment]
# ARマーカーによるカメラ位置推定
参考リンク：Qiita[Qiita](https://qiita.com/namahoge/items/69b4e2c66f5446dc8798)

**Comment by kazunosuke1108** [comment]
@masato1004 
検討ありがとう！端末のアプデが必要でフリーボードだけまだ確認できてないんだけど、他は確認しました！わかりやすくて助かります🙇
モジュールの放出についての検討も手が空き次第お願いします！以下、b班で検討してた案です。

3つモジュールを出す時に、一気に3つ出してしまうのではなく、一つずつ放出することとし、1つ出す度にローバの位置を調節して、初めから綺麗に並ぶように放出すれば、モジュールを出した後にそれを移動する作業が減るかな、、と。

ここでの議論事項についてはハードにも適宜共有しておきます(共有済みかもしれないけど)
無理ない範囲で引き続きお願いします！

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ミッション案具体的処理検討](https://trello.com/c/qzMN5QX0/7-%E3%83%9F%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E6%A1%88%E5%85%B7%E4%BD%93%E7%9A%84%E5%87%A6%E7%90%86%E6%A4%9C%E8%A8%8E)

**Comment by OtaKo50** [comment]
### ARマーカーの位置推定(距離)
[AR マーカを用いた距離推定に関する予備的検討.pdf](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/10880553/AR.pdf)

**Comment by kazunosuke1108** [comment]
@masato1004 
なるほど～　難しくないのであれば大丈夫だね！検討ありがとう！

フリーボードも見ました！見やすくてよいね
メンバー全員が確認できるように，フリーボードのスクショは3/6のMTG資料に貼っておきます～

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ミーティングスライド作成](https://trello.com/c/4dux6oen/8-%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E4%BD%9C%E6%88%90)
