### ISSUE TITLE
モジュール移動について

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#13]
# モジュールの移動に際して難しい点
参考issue： #12 
* 機体(カメラ)とモジュールの位置関係の推定方法
* 機体(カメラ)に対するモジュールの向きの推定方法.  
  * 接続面が上に来ているかどうか
* モジュール同士の位置関係の推定方法
* モジュール同士の位置関係が正しいかどうかの判断基準
* モジュールの移動戦略の立て方.  
  * 画像航法？？など，えられている情報から機体をどう動かすかの判断

ARマーカーが本当に優秀？

**Comment by suzukiYU000** [comment]
### 図形認識系
→モジュールの探索

- 「輪郭から四角形を検出」　https://qiita.com/sitar-harmonics/items/ac584f99043574670cf3
- 「画像中の図形検出」　https://tatsy.github.io/programming-for-beginners/python/figure-detection/

### ARマーカー系
→モジュールとの位置関係
→モジュールの向き

- 「ArUcoマーカーでカメラ位置姿勢の取得」　https://qiita.com/namahoge/items/69b4e2c66f5446dc8798
- 「pythonでARマーカーの姿勢推定」　https://qiita.com/ReoNagai/items/a8fdee89b1686ec31d10

**Comment by masato1004** [comment]
@suzukiYU000 
いいね！
それぞれの要素技術を使うと、このミッションではどんなことに使えるか、も一緒にお願いします！
コメントは編集できるから編集してもらってもいいし別で追記してもらっても！

**Comment by masato1004** [comment]
> # モジュールの移動に際して難しい点
> 参考issue： #12
> 
> * 機体(カメラ)とモジュールの位置関係の推定方法
> * 機体(カメラ)に対するモジュールの向きの推定方法.
>   
>   * 接続面が上に来ているかどうか
> * モジュール同士の位置関係の推定方法
> * モジュール同士の位置関係が正しいかどうかの判断基準
> * モジュールの移動戦略の立て方.
>   
>   * 画像航法？？など，えられている情報から機体をどう動かすかの判断
> 
> ARマーカーが本当に優秀？

## 3/4結論
* 移動戦略に関しては保留
* その他推定関連はARがそれなりに使えそう

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ミーティングスライド作成](https://trello.com/c/4dux6oen/8-%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E4%BD%9C%E6%88%90)
