### ISSUE TITLE
モジュールの接続について

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#14]
# モジュールの接続に際して難しい点
参考issue： #12 
* 導線の認識方法.  
  * 色？ARマーカー？その他識別方法.  
* 所望の位置に導線が到達しているかの判断方法
* 掴んだ導線の移動戦略
* 掴めたかどうかの判断方法

**Comment by kazunosuke1108** [comment]
@masato1004 @OtaKo50 
検討ありがとう！
ハード班の昨日のmtgで、導線の接続に際し、マニピュレータが導線を把持するか否かって議論が出てました！
導線を把持するには掴むためのモータが必要で、重さというハード面、制御というソフト面、どちらにおいても不利だろう、とのこと。
把持せず掴む方法として、導線をマニピュレータの先についた爪？でひっかけて動かすというアイデアが出てました！多分向こうもまだ詳細検討には至ってないけど、ソフトの要望を投げるなら今説あるので共有します〜

**Comment by OtaKo50** [comment]
###ARマーカーの位置推定(距離)
[AR マーカを用いた距離推定に関する予備的検討.pdf](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/10880591/AR.pdf)

**Comment by OtaKo50** [comment]
### ロボットの掴む判断
アームの先端に貼るシートタイプのセンサ
https://connect.nissha.com/filmdevice/shear-force-sensor/robot/?gclid=Cj0KCQiA0oagBhDHARIsAI-BbgcuomaFHOFjcq4OAFccxrlA6jEi8nM7iX1DFi0jbNpfjXrkhNBmZ0waAkx0EALw_wcB

**Comment by OtaKo50** [comment]
### ARマーカー以外の位置推定
raspberryPiにディープラーニングによる物体の位置検出をさせた例
https://murasan-net.com/index.php/2022/02/12/post-613/ 
ただし、実装後の検出精度は低そう
https://murasan-net.com/index.php/2022/04/24/post-1701/#index_id4

**Comment by masato1004** [comment]
@OtaKo50  
# 導線の認識と位置の判断
> ### ARマーカーの位置推定
> [AR マーカを用いた距離推定に関する予備的検討.pdf](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/10880591/AR.pdf)
> 
> ARマーカーで読み取ってロボットの座標系のマーカーの位置を算出する 誤差を及ぼす原因としてジッタと呼ばれる現象がある https://www.jstage.jst.go.jp/article/pscjspe/2019A/0/2019A_268/_pdf/-char/ja

## FB
* 同線の認識方法としてはARがやっぱいいのかな？ARマーカー張るとしたら面を確保しなきゃだけどどう実現しようね．．．
***
# ロボットの掴む判断
> アームの先端に貼るシートタイプのセンサ
> https://connect.nissha.com/filmdevice/shear-force-sensor/robot/?gclid=Cj0KCQiA0oagBhDHARIsAI-BbgcuomaFHOFjcq4OAFccxrlA6jEi8nM7iX1DFi0jbNpfjXrkhNBmZ0waAkx0EALw_wcB

## FB
* アームらしいアームをつけられたらこれいいかもしれないけど，ひっかけるとか電磁石とかの低コストアームだった場合はどんなのがあるかな，，，  
  * **つかむ判断≒移動させられている判断**？とかだとどんなのが考えられたりするかな
***
# ARマーカー以外の位置推定
> ## ディープラーニング
>・raspberryPiにディープラーニングによる物体の位置検出をさせた例
> [https://murasan-net.com/index.php/2022/02/12/post-613/](https://murasan-net.com/index.php/2022/02/12/post-613/)
>ただし、実装後の検出精度は低そう
> [https://murasan-net.com/index.php/2022/04/24/post-1701/#index_id4](https://murasan-net.com/index.php/2022/04/24/post-1701/#index_id4)
> 
> ## 色を用いたもの
> ・物体の位置を識別はできるが、掴むための向きや距離は難しい。照明条件に依存していることから難しい？
> [https://qiita.com/hsgucci/items/e9a65d4fa3d279e4219e](https://qiita.com/hsgucci/items/e9a65d4fa3d279e4219e)
> ・横から光を当てて3次元計測を行う例→周囲環境を作るのが厳しい
> file:///Users/otako/Downloads/IPSJ-MIRU2011205.pdf
> ・カラー開口撮像技術という2色のフィルタのぼけ具合から距離推定する手法
> 面白そうだけど、向きの特定は難しそう。また、これを利用できる距離をcansatサイズにできないかも？
> [https://www.jstage.jst.go.jp/article/itej/71/9/71_634/_pdf](https://www.jstage.jst.go.jp/article/itej/71/9/71_634/_pdf)

## FB
* 去年に引き続き低コスト・低処理能力CPUに学習を使用するのはすごく面白そう！  
  * おそらく事前学習の形になると思うけど，どんな画像をどのくらい用意する必要がありそう？
  * モジュールの接続において何を学習させてどう使用する？？  
* RGBのみによる推定がcansatサイズで出来たら確かに面白そうだしその手法の有用性を示せそうで面白い！  
***

# 全体FB
いろんな要素技術を学術ベースで調べてくれていてとてもいいと思います！
これらの技術を使用して実際のミッションを行うときに，もっと**詳細な場面と活用方法**
* この作業を行うときのこの動作を行うために～の技術を応用して～のように活用することで，～という難しさを克服できるのではないか  

とかまでさらに書いてくれるとMTGに向けてまとまりやすくなると思う!!
## 余談
同線みたいな形状がはっきりしないものの認識と把持ってそもそも結構難しい話な気がしているので，別の視点として
**cansatでもできそうなレベル感に要求される動作レベルを落とす**
みたいなのももっていてもいいかもしれない．．．？

**Comment by masato1004** [comment]
> # モジュールの接続に際して難しい点
> 参考issue： #12
> 
> * 導線の認識方法.
>   
>   * 色？ARマーカー？その他識別方法.
> * 所望の位置に導線が到達しているかの判断方法
> * 掴んだ導線の移動戦略
> * 掴めたかどうかの判断方法

## 3/4結論
* 認識関連はARが有用そう.  
  * ARを貼る部分の確保.  
* 移動戦略に関しては保留（情報収集継続）

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ミーティングスライド作成](https://trello.com/c/4dux6oen/8-%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E4%BD%9C%E6%88%90)
