### ISSUE TITLE
ARマーカープロトタイプ作成

### ISSUE THREAD

**Issue by OtaKo50** [KeioTeamWolvez2023/wolvez2023-soft#15]
@OtaKo50 
#  ARマーカーの可能性調査
最小サイズの調査
***
## 位置・姿勢推定・向き推定の関数作成
* 引数.  
  * 画像に関しては今回はファイルのパス指定.  
  * 画像の縦横比を変数で定義
* 関数の説明.  
  * 引数，使用するライブラリ，戻り値，特筆すべき変数など.  
* 戻り値.  
  * 位置(カメラローカル座標，ARマーカー座標)，単位法線ベクトル.  
* その他.  
  * デバッグ用にAR座標軸表示（できれば）

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AR実践&最小サイズ検討](https://trello.com/c/PDcDIgXX/10-ar%E5%AE%9F%E8%B7%B5%E6%9C%80%E5%B0%8F%E3%82%B5%E3%82%A4%E3%82%BA%E6%A4%9C%E8%A8%8E)

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ラズパイカメラ使用環境構築](https://trello.com/c/iK6Wewes/11-%E3%83%A9%E3%82%BA%E3%83%91%E3%82%A4%E3%82%AB%E3%83%A1%E3%83%A9%E4%BD%BF%E7%94%A8%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [進捗確認MTG](https://trello.com/c/CgqOhtXp/14-%E9%80%B2%E6%8D%97%E7%A2%BA%E8%AA%8Dmtg)

**Comment by masato1004** [comment]
# 開発メモ
* ラズパイカメラ画像サイズ：640*480
* 機体の15cm先にある1cm四方の上向きマーカーの認識可能
* 使用カメラが変更される場合にはキャリブレーションが必要
* ピントをいじるといいかもしれない

**Comment by masato1004** [comment]
@KeioTeamWolvez2023/leaders 
@KeioTeamWolvez2023/soft 
# 超初期検討最小サイズ
## 結論
・とりあえず超初期検討最小1cm！
***
## 注意事項
・光の反射はシビア
・ **ピントがあえば40cm先の1cmも読める**（カメラ方向を向けた場合）
  > ![image](https://user-images.githubusercontent.com/92346511/225307301-5290a580-b931-4561-a661-be281b943625.png)  
　・合わなければ20cmも無理  
    > ![image](https://user-images.githubusercontent.com/92346511/225307471-2437c6fb-84a3-4ff7-84e1-b42eb85c2f54.png)

・上向きはモジュールサイズを考えると難しいかもしれない
　・15cm以下であれば上向きでも測定可能
***
## 今後の方針
@suzukiYU000 @OtaKo50 
* 最適なピント位置の調整
* 別材質での検討
* 照明条件にロバストな画像航法（反射をどう対処するか）

**Comment by OtaKo50** [comment]
# 3.18 開発検討メモ
今のディクショナリで使えそうなマーカー番号
771.768.683.682.640.337.325.257.258.85
白と黒が隣り合ってないマークが良さそう

**Comment by OtaKo50** [comment]
## 認識精度検証結果
[CanSat_カメラ精度テスト.xlsx](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/11010642/CanSat_.xlsx)

**Comment by masato1004** [comment]
# プロトタイプ作成完了
## 使用感（動画）
[**ARマーカー認識検証動画リンク**](https://drive.google.com/file/d/1_FZ0_RjBAwUu7onhcEEZU6l4VXu5VYZy/view?usp=drive_web)
## 現段階の結論
* ピントが非常に大きく影響➡︎オートフォーカス機能付きのカメラ推奨
* 1 cmでも反応できる距離範囲もあるが，大きいに越したことはない.  
  * 2 cmにするだけでかなり違う.  
* 精度はかなり高い.  
  * 認識していれば**おおよそ 0.5 ~ 5% のずれに収まる**(近距離≒高精度)
