### ISSUE TITLE
配線の目標点追従

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#16]
# ARマーカーを用いた配線の移動
#15 (ARマーカーのプロトタイプ作成)
## 本issueのゴール
**ARマーカーの認識を利用した，配線を適切な位置へ移動するアルゴリズムの検討・実装**  

以下ex.)  
* ARマーカーの認識を利用して現在の座標から目標点へのベクトルを生成する
## 行うこと
* 通信モジュールの位置をもとにした配線モジュールの目標空間の定義？
* 配線の座標から目標空間中心へのベクトルを算出？≔目標ベクトル
* 目標ベクトルから機体の動きの生成  
  * 前後移動距離
  * 左右回転角

**Comment by masato1004** [comment]
# アルゴリズム案検討
* **モジュール本体にはどちらも2 cmマーカー，配線には1 cm**
* アームの先端にマーカーをつけて，カメラからの情報として取得する.  
  * モジュールとアーム先端の位置関係を認識しやすくなる.  
* 配線の出てくる位置（ハード的要求）.  
  * 配線先端が横向きになるように最初の固定をする.  
* モジュール二つと機体で二等辺三角形を作る？  
* モジュール同士を話して放出する説？  
  * 機体が小さい回転を生めるのであればモジュールが近くてもいい

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [配線の移動アルゴリズム検討](https://trello.com/c/8Liah3QG/13-%E9%85%8D%E7%B7%9A%E3%81%AE%E7%A7%BB%E5%8B%95%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E6%A4%9C%E8%A8%8E)

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [機体の最小回転角検証](https://trello.com/c/bIimxQt9/15-%E6%A9%9F%E4%BD%93%E3%81%AE%E6%9C%80%E5%B0%8F%E5%9B%9E%E8%BB%A2%E8%A7%92%E6%A4%9C%E8%A8%BC)

**Comment by masato1004** [comment]
# モーターの瞬間出力
* 高出力でも出力時間を調節すれば意外といける
  ```py
  time.sleap(0.03)
  ```
  https://user-images.githubusercontent.com/92346511/226533033-ea488e96-14a6-488f-b1c9-e8a571663b0b.mp4

**Comment by suzukiYU000** [comment]
https://user-images.githubusercontent.com/126460582/226582815-c1a4a566-b845-40ba-9bb2-1ca885a03e95.mp4

**Comment by masato1004** [comment]
# 配線移動のアルゴリズム検討
@KeioTeamWolvez2023/soft 
## フローチャートの作成
**考慮すべきこと**
* まずid「１」まである程度近づく
* 放出はうまくいっている想定
* 決定するのは左右のモーター出力

**Comment by masato1004** [comment]
# 3/24開発メモ
## 実装内容
* モジュール一つに対する機体の目標位置判定関数
## 難しくなる点
* **モジュールの角度**を重視した近づき方
* 無駄のない経路計画.  
  * 正しい位置＆向きへの移動

**Comment by masato1004** [comment]
https://user-images.githubusercontent.com/92346511/227498499-1451e1a5-6435-495a-a35f-966793426e60.MOV

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [配線の移動アルゴリズム検討](https://trello.com/c/8Liah3QG/13-%E9%85%8D%E7%B7%9A%E3%81%AE%E7%A7%BB%E5%8B%95%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E6%A4%9C%E8%A8%8E)

**Comment by OtaKo50** [comment]
### 配線を掴む処理のの検討
[/Users/otako/Downloads/配線を掴む検討.pptx](url)

**Comment by OtaKo50** [comment]
### 配線を掴む処理の検討
<img width="873" alt="スクリーンショット 2023-03-31 18 45 55" src="https://user-images.githubusercontent.com/126455140/229086499-3b43e59f-85b1-4b68-b0d1-e1e8ae3f4aa0.png">

**Comment by OtaKo50** [comment]
### 補足
・アームが斜めのメジャーでも計算が複雑になるだけで、高低差に対応することはできそう
・さらに、アームがまっすぐなものと比べてカメラから二つのマーカーが見えやすいのでこの処理を数回繰り返して誤差を小さくすることはできそう

**Comment by masato1004** [comment]
# FB
to: @OtaKo50 
Cc: @suzukiYU000 （意見上記検討について意見あれば是非！）
## 仮定について
> アームと配線のつかむ部分の高さは等しい

平面上の動きの検討としては置いたほうが考えやすい仮定ではあるけど，**実際の環境では高確率で成り立たない**ものだと思うので，アームと配線のつかむ部分の高さが異なるときのサーボモーター制御も含めた接近手法も考えられると良いかも

## 位置追従の順序について
* よくわかってないかもなんだけど，**4.の角度と距離の算出はどこのこと**？もしアームから配線までの話であればベクトルひとつ求まれば解決する問題ではない？
* 全体的に文言と機体の動きのイメージがつきにくいので，もう少し詳細な図とテキストを対応させてもらえるとわかりやすい！

## 検討について
> アームが斜めのメージャーを回転させるタイプの場合，環境による高低差に対応できない？

仮定としておいている部分の内容なので，今回なぜそれを仮定としておけて，斜めのタイプではなぜ置けないのかの説明もあると，この検討が必要になる理由が明確になると思う！

**Comment by OtaKo50** [comment]
たしかに！ベクトル一つ求めれば良いのは気づかなかったです！

上のコメントのような二つのベクトルから正しいベクトルを求めるやり方は、上下方向に適用すれば実際の地面に沿ったベクトルを求めることができるので、高低差の修正に使えると思います！

**Comment by OtaKo50** [comment]
### 位置追従の順序についてのFBに関して
実際の環境だとモータへの指令値に対してどのくらい動くかわからないので、ベクトル一つ求めるだけでは足りないと考えました！
次回から図示頑張ります

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [アルゴリズム検討現状まとめ](https://trello.com/c/WqzkPOUJ/18-%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E6%A4%9C%E8%A8%8E%E7%8F%BE%E7%8A%B6%E3%81%BE%E3%81%A8%E3%82%81)

**Comment by OtaKo50** [comment]
### 接近の時に使えそうなこと
元々話に出ていたAI(カラーコーンに接近するやつ)を併用して使えば、一旦建てた経路を修正しながら接近できそう

### 気づいたこと
機体が二等辺三角形の頂点にいる状態から配線を掴む
↓
せっかく二等辺三角形の頂点にいるのに、導線を掴むために片方のモジュールに近付いてしまうのは勿体無い
↓
切れ込みの位置をメジャーの側面に変更して、機体の回転で導線を引っ掛けた方が良さそう
(モジュール同士の距離がアームの長さの2倍にならない前提)

切れ込みの位置と図は、今難しいので後日貼ります

**Comment by masato1004** [comment]
# FB
* AIの具体的な使用方法についてをメモ程度（検討段階）としてスライドに載せられると良い！  
  * 学習させる内容
  * 学習した結果，何を与えると何が返ってくるのか  
* つかみに行くことで二等辺三角形の頂点に移動できるような位置に止まればよい？
➡ [**Dubins path**](https://myenigma.hatenablog.com/entry/2017/05/01/144956)っていう経路生成があるらしい
#18

**Comment by masato1004** [comment]
# スライドについて
@OtaKo50 
* 図中のそれぞれが何を表しているのかをキャプションつけておいて！
* スライドは基本体言止めで！（cansatに限らず）
ついでにもう少し文字数を減らしたい感あるからもしコンパクトになりそうなとこがあったら削っちゃってもらえると！

**Comment by OtaKo50** [comment]
ベクトル計測によって発生する絶対誤差の和を最小化する統計的軌道決定アプローチ
[Least Sum of Absolute Residuals Orbit Determination.pdf](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/11182795/Least.Sum.of.Absolute.Residuals.Orbit.Determination.pdf)

**Comment by OtaKo50** [comment]
大きなポーズシフトを持つオブジェクトを追跡するための、ロバストで正確な単眼ポーズ追跡法を提案
[Robust and Accurate Monocular Pose Tracking for Large Pose Shift.pdf](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/files/11182838/Robust.and.Accurate.Monocular.Pose.Tracking.for.Large.Pose.Shift.pdf)

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [移動アルゴリズムの検討・実装検証](https://trello.com/c/Ce2zJPGO/19-%E7%A7%BB%E5%8B%95%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E3%81%AE%E6%A4%9C%E8%A8%8E%E3%83%BB%E5%AE%9F%E8%A3%85%E6%A4%9C%E8%A8%BC)
