### ISSUE TITLE
オートフォーカスカメラ

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#20]
#  オートフォーカス機能付きラズパイカメラ
従来使用していたラズパイカメラと同じ方法では使用できないっぽいので，使えるようになるまでの検討段階をまとめていきます．
## 使用ラズパイカメ
[**16MP IMX519**](https://www.switch-science.com/products/7681)
![image](https://user-images.githubusercontent.com/92346511/231068807-9663317a-3b96-45c8-8b3a-169ac2fba6c9.png)
## 現段階での課題点
* ap化に対応しているOS（legacy）とオートフォーカスカメラに対応しているOS（最新）が異なる可能性
* ~openCVのインストールが終わらない~
* 結局まだカメラが使えていない.  
  * `cameratest.py`を使用しても，ネットに書いてあるコマンドを使っても撮影できない
  * やばい

**Comment by 19238901** [comment]
＃オートフォーカスカメラ実装のブログ
[https://docs.arducam.com/Raspberry-Pi-Camera/Native-camera/Quick-Start-Guide/](https://docs.arducam.com/Raspberry-Pi-Camera/Native-camera/Quick-Start-Guide/)

**Comment by 19238901** [comment]
OpenCVインストール手順
※pythonのバージョンに合わせる
https://python-academia.com/raspberrypi-opencv/
- ラズパイの更新
- pipの更新
- 依存関係にあるライブラリのインストール

**Comment by masato1004** [comment]
# Use `libcamera` in python code
shuld be imported `libcamera` library in python code

**Comment by 19238901** [comment]
```py
#!/usr/bin/python3
import time

import cv2

from picamera2 import MappedArray, Picamera2, Preview

# This version creates a lores YUV stream, extracts the Y channel and runs the face
# detector directly on that. We use the supplied OpenGL accelerated preview window
# and delegate the face box drawing to its callback function, thereby running the
# preview at the full rate with face updates as and when they are ready.

face_detector = cv2.CascadeClassifier("/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml")


def draw_faces(request):
    with MappedArray(request, "main") as m:
        for f in faces:
            (x, y, w, h) = [c * n // d for c, n, d in zip(f, (w0, h0) * 2, (w1, h1) * 2)]
            cv2.rectangle(m.array, (x, y), (x + w, y + h), (0, 255, 0, 0))


picam2 = Picamera2()
picam2.start_preview(Preview.QTGL)
config = picam2.create_preview_configuration(main={"size": (640, 480)},
                                             lores={"size": (320, 240), "format": "YUV420"})
picam2.configure(config)

(w0, h0) = picam2.stream_configuration("main")["size"]
(w1, h1) = picam2.stream_configuration("lores")["size"]
s1 = picam2.stream_configuration("lores")["stride"]
faces = []
picam2.post_callback = draw_faces

picam2.start()

start_time = time.monotonic()
# Run for 10 seconds so that we can include this example in the test suite.
while time.monotonic() - start_time < 10:
    buffer = picam2.capture_buffer("lores")
    grey = buffer[:s1 * h1].reshape((h1, s1))
    faces = face_detector.detectMultiScale(grey, 1.1, 3)
```

**Comment by 19238901** [comment]
[サンプルコード](https://github.com/raspberrypi/picamera2)

**Comment by 19238901** [comment]
[Arducamの高解像度カメラを使う](https://note.com/arcana_tech/n/n59cb4cd2583e)

**Comment by 19238901** [comment]
```py
import cv2
from datetime import datetime

# /dev/video0を指定
DEV_ID = 0

# パラメータ
WIDTH = 640
HEIGHT = 480

def main():
    # /dev/video0を指定
    cap = cv2.VideoCapture(DEV_ID)

    # 解像度の指定
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, HEIGHT)

    # キャプチャの実施
    ret, frame = cap.read()
    if ret:
        # ファイル名に日付を指定
        date = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = "./" + date + ".jpg"
        cv2.imwrite(path, frame)

    # 後片付け
    cap.release()
    cv2.destroyAllWindows()
    return


if __name__ == "__main__":
    main()
```

**Comment by masato1004** [comment]
> 旧OSでAFカメラを使用できる？ [Arducamの高解像度カメラを使う](https://note.com/arcana_tech/n/n59cb4cd2583e)

- 試したもののカメラ起動せず
- OSの`Buster`と`Bullseye`の違いは致命的？
## 現段階の方針
**旧OS(Buster)でのオートフォーカスカメラの使用は一旦諦め，新OS(Bullseye)でのAccess Point 化の実装を目指す**

**Comment by 19238901** [comment]
[BullseyeでAP化](https://www.mikan-tech.net/entry/raspi-wifi-ap)

**Comment by masato1004** [comment]
# Capture with IMX519
![test](https://user-images.githubusercontent.com/92346511/233772337-6775ae96-3fc2-46e4-95c8-191910ba4e6f.jpg)

**Comment by masato1004** [comment]
# オートフォーカスカメラの使用感
## 画質
* 何もいじっていない状態の写真のサイズはナント驚異の`4656 x 3496`  
  * これだけ離れていても文字読める
  > ![IMG_8129](https://user-images.githubusercontent.com/92346511/233773239-499d4894-40a7-49ea-a1d3-ca488ff9c6e1.jpeg)  
* 変更方法は以下とか（[**`pycamera2`公式ドキュメント**](https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf)参照）  
  `picam2.create_still_configuration(lores={"size": (320, 240)}, display="lores")`
## オートフォーカスについて
* 検証中

**Comment by masato1004** [comment]
https://user-images.githubusercontent.com/92346511/234528940-f677a650-1859-4ad3-98b5-51994a838679.mp4
