### ISSUE TITLE
能代前進捗記録

### ISSUE THREAD

**Issue by masato1004** [KeioTeamWolvez2023/wolvez2023-soft#29]
# 用途
@KeioTeamWolvez2023/soft 
能代大会までの開発の記録を各々が日記的に記録
自分が開発に関わった日は必ずメモ

**Comment by masato1004** [comment]
# GPS走行算出の式メモ
<img width="510" alt="image" src="https://github.com/KeioTeamWolvez2023/wolvez2023-soft/assets/92346511/66ef3e02-86fb-4392-ba11-993ff83c9692">

**Comment by kazunosuke1108** [comment]
# gps running test results
![gpsrun2](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/assets/100997999/b6650995-a815-4216-832a-decb199355be)
![gpsrun1](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/assets/100997999/8de1413c-8da5-418b-9628-681e96cd7254)

**Comment by masato1004** [comment]
# 回転ベクトルを使用した座標の回転
[回転ベクトルからその他回転表現へ](https://kamino.hatenablog.com/entry/scipy_rotation)

**Comment by masato1004** [comment]
# Blue range
![10-20230731175917](https://github.com/KeioTeamWolvez2023/wolvez2023-soft/assets/92346511/24cca8d7-aa51-4ae5-a4c9-31bdd33335d6)
