### ISSUE TITLE
# 0208MTGについて

### ISSUE THREAD

**Issue by kazunosuke1108** [KeioTeamWolvez2023/wolvez2023-soft#6]
# MTGの進行予定

## M1のプレゼン

- MTGの流れの紹介
- CanSatとは
- CanSatを通じて得られること
- CanSatの分担・班長紹介
- 班分け説明
    - ハード・回路班長より
    - ソフト班長より
- 大会について
    - 日程面（ツアコン）
    - 資金面（会計）

## 協議
- B4からの質疑
- B4の希望調査
- B4の振り分け
- 欠席者の振り分け

**Comment by Masato104** [comment]
> @Masato104 
> こんなもんかね（ほんとは全員メンションしたいけど不在なので）

@kazunosuke1108 
良きだと思う！
今後ハード班用のリポジトリも一応作る予定！
ファイルの共有とかはgithubを強制しないけど，issuesとかうまく使ってもらえれば！みたいな！

**Comment by kazunosuke1108** [comment]
@Masato104 @murayamashingo
全体の流れ作ってみた！コメントほしい！！
https://docs.google.com/presentation/d/14xSUu8hrcPqpRvSGpvXPDGuGGypUh6Va/edit#slide=id.p1

**Comment by Masato104** [comment]
@kazunosuke1108 
> 全体の流れ作ってみた！コメントほしい！！全体の流れ作ってみた！コメントほしい！！  

流れはいい思う！
以下諸修正点
***
* カムバック　➡　ランバック
* ソフトの説明は林出担当？？
* 基本大会は参加だけど諸事情により不参加もあります！みたいな予防線もあると気が楽？？

**Comment by kazunosuke1108** [comment]
@Masato104 
ありがとう！
> カムバック　➡　ランバック
草　直すわw
> ソフトの説明は林出担当？？
できるよ！けどなんというか，全員に発言する機会を持ってほしいから可能であれば将利もぜひ！
> 基本大会は参加だけど諸事情により不参加もあります！みたいな予防線もあると気が楽？？
そうだね〜，一応口頭で言うようにするけど忘れてるかもだからその時は口挟んで！

**Comment by Masato104** [comment]
@kazunosuke1108 
> できるよ！けどなんというか，全員に発言する機会を持ってほしいから可能であれば将利もぜひ！  
するする！んだけどスライド林出になってたから林出やるんかと思た！井上やります

**Comment by kazunosuke1108** [comment]
@Masato104

んえまじか！直す直す！ありがとう！！

2023年2月7日(火) 23:44 Masato ***@***.***>:

**Comment by murayamashingo** [comment]
すげgithubってこんなこともできるんですね
gmailにもくるんね
今からみます

**Comment by murayamashingo** [comment]
@Masato104 @kazunosuke1108 
はヤシで全体スライド作りありがとう
スライドいい感じだとおもう！
gitの使い方に頑張って慣れていきます
当日は回路とハードのスライドを別々に用意してます

**Comment by masato1004** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [テスト](https://trello.com/c/U6cIPTY4/6-%E3%83%86%E3%82%B9%E3%83%88)
